branch-defaults:
  main:
    environment: flask-h3-env
    group_suffix: null
global:
  application_name: overture-places-h3-search-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
